added semver check to publish workflow

diff --git a/.github/workflows/publish-crates-io.yml b/.github/workflows/publish-crates-io.yml
--- a/.github/workflows/publish-crates-io.yml
+++ b/.github/workflows/publish-crates-io.yml
@@ -36,12 +36,17 @@ jobs:
       - name: Install cargo-workspaces
         run: cargo install cargo-workspaces
 
-      # - name: Validate version format
-      #   run: |
-      #     if ! npx semver "${{ inputs.version }}"; then
-      #       echo "Error: '${{ inputs.version }}' is not valid semver"
-      #       exit 1
-      #     fi
+      - name: Setup Node.js
+        uses: actions/setup-node@v4
+        with:
+          node-version: "20"
+
+      - name: Validate version format
+        run: |
+          if ! npx semver "${{ inputs.version }}"; then
+            echo "Error: '${{ inputs.version }}' is not valid semver"
+            exit 1
+          fi
 
       - name: Get current version
         id: current_version
@@ -51,7 +56,7 @@ jobs:
 
       - name: Update workspace dependencies
         run: |
-          sed -i 's/version = "${{ steps.current_version.outputs.version }}"/version = "${{ inputs.version }}"/g' Cargo.toml
+          sed -i '/path = /s/version = "${{ steps.current_version.outputs.version }}"/version = "${{ inputs.version }}"/g' Cargo.toml
 
       - name: Bump versions and push
         run: |
@@ -59,7 +64,15 @@ jobs:
             --no-git-tag \
             --yes
 
+      # For the first publish, we have to run with this very long cooldown. That is due to the
+      # crates.io rate limiting. Once the initial publication is done, then this interval can
+      # be reduced to 60 seconds.
+      # See https://github.com/rust-lang/crates.io/blob/ad7e58e1afd65b9137e58a7bca3e1fb7f5546682/src/rate_limiter.rs#L228 for code comments about this.
       - name: Publish
         env:
           CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}
-        run: cargo workspaces publish --no-git-commit --allow-dirty --publish-interval 600
+        run: cargo workspaces publish --no-git-tag --allow-dirty --publish-interval 600
+
+      # Show the list of packages published
+      - name: Show package versions
+        run: cargo workspaces list --long
